### ISSUE TITLE
alternative api

### ISSUE THREAD

**Issue by eivindfjeldstad** [koajs/override-method#1]
would you consider changing the api to `override(ctx, body)`? using `.call` feels a little weird, at least to me

**Comment by eivindfjeldstad** [comment]
nah, nvm. it's such a small utility, i'll just write my own:)

**Comment by jonathanong** [comment]
yeah it's so small. i just don't like the other APIs. i don't even use this.

**Comment by jonathanong** [comment]
imo it should support both, but i'm too lazy to support it

**Comment by tj** [comment]
yea I agree .call() is a little funky, I'd only really use .call() when you explicitly want to change a receiver for methods

**Comment by jonathanong** [comment]
i like using `.call()` because i can easily use fns as either middleware, decorators, or just functions. or i can be crazy and do `app.context.methodOverride = require('override-method')`.
